'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { useAuth } from '../../../../context/AuthContext';
import { apiService } from '../../../../lib/api';
import { Card } from '../../../../components/ui/index';
import { ArrowLeft, Save, RefreshCw, Lock, Eye, EyeOff } from 'lucide-react';

export default function NewUserPage() {
  const router = useRouter();
  const { user: currentUser } = useAuth();
  
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [generatedPassword, setGeneratedPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);

  const [formData, setFormData] = useState({
    email: '',
    full_name: '',
    role: 'staff',
    password: '' // Optional - will be generated if empty
  });

  const isAdmin = currentUser?.role === 'super_admin' || currentUser?.role === 'admin';

  const handleGeneratePassword = async () => {
    try {
      const result = await apiService.generatePassword();
      const password = result.password || result.generated_password;
      setFormData(prev => ({ ...prev, password }));
      setGeneratedPassword(password);
      setShowPassword(true);
    } catch (err: any) {
      setError('Erreur lors de la génération du mot de passe');
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaving(true);
    setError('');
    setSuccess('');

    try {
      const result = await apiService.createUser(formData);
      
      // If password was generated by backend
      if (result.generated_password) {
        setGeneratedPassword(result.generated_password);
        setShowPassword(true);
        setSuccess(`Utilisateur créé avec succès! Mot de passe: ${result.generated_password}`);
      } else {
        setSuccess('Utilisateur créé avec succès!');
      }
      
      // Redirect after 3 seconds
      setTimeout(() => {
        router.push('/admin/users');
      }, 3000);
    } catch (err: any) {
      setError(err.message || 'Erreur lors de la création de l\'utilisateur');
    } finally {
      setSaving(false);
    }
  };

  const handleChange = (field: string, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  if (!isAdmin) {
    return (
      <div className="p-6">
        <div className="bg-red-50 border border-red-200 rounded-xl p-6 text-center">
          <h2 className="text-xl font-semibold text-red-800 mb-2">Accès Refusé</h2>
          <p className="text-red-600">
            Vous n'avez pas les permissions nécessaires pour créer des utilisateurs.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="p-6 max-w-2xl mx-auto">
      {/* Header */}
      <div className="flex items-center gap-4 mb-6">
        <Link
          href="/admin/users"
          className="p-2 text-stone-600 hover:text-amber-600 hover:bg-amber-50 rounded-lg transition-all duration-200"
        >
          <ArrowLeft className="w-5 h-5" />
        </Link>
        <div>
          <h1 className="text-3xl font-light text-stone-800">Nouvel Utilisateur</h1>
          <p className="text-stone-600 mt-1">
            Créer un nouveau compte utilisateur
          </p>
        </div>
      </div>

      {/* Success Message */}
      {success && (
        <div className="bg-green-50 border border-green-200 text-green-700 px-4 py-3 rounded-xl mb-6">
          {success}
          {generatedPassword && (
            <div className="mt-2 p-3 bg-white rounded border border-green-300">
              <p className="font-semibold mb-1">⚠️ Sauvegardez ce mot de passe maintenant!</p>
              <p className="font-mono text-sm">{generatedPassword}</p>
            </div>
          )}
        </div>
      )}

      {/* Error Message */}
      {error && (
        <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-xl mb-6">
          {error}
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* User Info Card */}
        <Card className="p-6 lg:col-span-2">
          <h2 className="text-xl font-semibold text-stone-800 mb-4">
            Informations de l'utilisateur
          </h2>
          
          <form onSubmit={handleSubmit} className="space-y-6">
            {/* Email */}
            <div>
              <label className="block text-sm font-medium text-stone-700 mb-2">
                Email *
              </label>
              <input
                type="email"
                required
                value={formData.email}
                onChange={(e) => handleChange('email', e.target.value)}
                className="w-full px-4 py-3 border border-stone-300 rounded-xl focus:ring-2 focus:ring-amber-500 focus:border-transparent"
                placeholder="utilisateur@example.com"
              />
            </div>

            {/* Full Name */}
            <div>
              <label className="block text-sm font-medium text-stone-700 mb-2">
                Nom Complet *
              </label>
              <input
                type="text"
                required
                value={formData.full_name}
                onChange={(e) => handleChange('full_name', e.target.value)}
                className="w-full px-4 py-3 border border-stone-300 rounded-xl focus:ring-2 focus:ring-amber-500 focus:border-transparent"
                placeholder="Jean Dupont"
              />
            </div>

            {/* Role */}
            <div>
              <label className="block text-sm font-medium text-stone-700 mb-2">
                Rôle *
              </label>
              <select
                value={formData.role}
                onChange={(e) => handleChange('role', e.target.value)}
                className="w-full px-4 py-3 border border-stone-300 rounded-xl focus:ring-2 focus:ring-amber-500 focus:border-transparent"
              >
                <option value="staff">Staff</option>
                <option value="manager">Manager</option>
                {currentUser?.role === 'super_admin' && (
                  <option value="admin">Administrateur</option>
                )}
              </select>
              <p className="text-xs text-stone-500 mt-1">
                Staff: Accès de base | Manager: Gestion avancée | Admin: Contrôle total
              </p>
            </div>

            {/* Password */}
            <div>
              <label className="block text-sm font-medium text-stone-700 mb-2">
                Mot de passe
              </label>
              <div className="flex gap-2">
                <div className="flex-1 relative">
                  <input
                    type={showPassword ? "text" : "password"}
                    value={formData.password}
                    onChange={(e) => handleChange('password', e.target.value)}
                    className="w-full px-4 py-3 border border-stone-300 rounded-xl focus:ring-2 focus:ring-amber-500 focus:border-transparent pr-10"
                    placeholder="Laisser vide pour génération automatique"
                  />
                  {formData.password && (
                    <button
                      type="button"
                      onClick={() => setShowPassword(!showPassword)}
                      className="absolute right-3 top-1/2 transform -translate-y-1/2 text-stone-400 hover:text-stone-600"
                    >
                      {showPassword ? <EyeOff className="w-5 h-5" /> : <Eye className="w-5 h-5" />}
                    </button>
                  )}
                </div>
                <button
                  type="button"
                  onClick={handleGeneratePassword}
                  className="px-4 py-3 border border-stone-300 text-stone-700 rounded-xl hover:bg-stone-50 transition-all duration-200 flex items-center gap-2"
                >
                  <RefreshCw className="w-4 h-4" />
                  Générer
                </button>
              </div>
              <p className="text-xs text-stone-500 mt-1">
                Si vide, un mot de passe sécurisé sera généré automatiquement
              </p>
            </div>

            {/* Action Buttons */}
            <div className="flex gap-4 pt-6 border-t border-stone-200">
              <Link
                href="/admin/users"
                className="flex-1 px-6 py-3 border border-stone-300 text-stone-700 rounded-xl font-semibold text-center hover:bg-stone-50 transition-all duration-200"
              >
                Annuler
              </Link>
              <button
                type="submit"
                disabled={saving}
                className="flex-1 bg-amber-500 text-white px-6 py-3 rounded-xl font-semibold hover:bg-amber-600 transition-all duration-200 disabled:opacity-50 flex items-center justify-center gap-2"
              >
                {saving ? (
                  <>
                    <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
                    Création...
                  </>
                ) : (
                  <>
                    <Save className="w-5 h-5" />
                    Créer l'utilisateur
                  </>
                )}
              </button>
            </div>
          </form>
        </Card>

        {/* Help Card */}
        <Card className="p-6 h-fit">
          <h2 className="text-xl font-semibold text-stone-800 mb-4">Aide</h2>
          
          <div className="space-y-4 text-sm text-stone-600">
            <div>
              <h3 className="font-semibold text-stone-800 mb-1">📧 Email</h3>
              <p>Utilisé pour la connexion. Doit être unique.</p>
            </div>
            
            <div>
              <h3 className="font-semibold text-stone-800 mb-1">🔐 Mot de passe</h3>
              <p>Si vide, un mot de passe sécurisé sera généré automatiquement. Assurez-vous de le sauvegarder!</p>
            </div>
            
            <div>
              <h3 className="font-semibold text-stone-800 mb-1">👥 Rôles</h3>
              <ul className="list-disc list-inside space-y-1 mt-1">
                <li><strong>Staff:</strong> Accès de base</li>
                <li><strong>Manager:</strong> Gestion des stocks</li>
                <li><strong>Admin:</strong> Gestion complète</li>
              </ul>
            </div>
            
            <div className="border-t border-stone-200 pt-4">
              <div className="flex items-center gap-2 text-amber-600">
                <Lock className="w-4 h-4" />
                <span className="font-semibold">Sécurité</span>
              </div>
              <p className="mt-1">
                Les mots de passe générés respectent les critères de sécurité: 12+ caractères, majuscules, minuscules, chiffres et caractères spéciaux.
              </p>
            </div>
          </div>
        </Card>
      </div>
    </div>
  );
}